global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app'
    scrape_interval: 45s
    static_configs:
        - targets: [ 'app:5000', 'localhost:5000' ]

  - job_name: 'kafka'
    scrape_interval: 45s
    static_configs:
      - targets: [ 'localhost:9092' ]